import Head from "next/head";
import Link from "next/link";
import {
  SignIn,
  SignInButton,
  SignOutButton,
  UserButton,
  useAuth,
} from "@clerk/nextjs";
import { api } from "~/utils/api";

export default function Home() {
  const { isLoaded: userLoaded, isSignedIn } = useAuth();
  if (!isSignedIn) return <SignIn />;
  if (!userLoaded) return <div>...Loading user</div>;

  // const { data, isLoading } = api.post.getLatest.useQuery();
  // if (isLoading) return <div>...Loading</div>;
  // if (!data) return <div>Something went wrong</div>;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello world!</h1>
        {!isSignedIn && <SignInButton />}
        {!!isSignedIn && <SignOutButton />}
        {/* <p className="text-2xl text-black">{data.name}</p> */}
      </main>
    </>
  );
}
